

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: canchasdb
      POSTGRES_USER: abby
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runscript seed &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=canchasdb
      - DB_USER=abby
      - DB_PASSWORD=secret
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
