# Generated by Django 5.2 on 2025-04-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolideportivoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='polideportivos/')),
            ],
        ),
    ]
