# Generated by Django 5.2 on 2025-04-27 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolideportivoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='polideportivos/')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polideportivos', to='users.propietario')),
            ],
        ),
    ]
